#!/bin/sh

# Sample setup for '/etc/munin/plugin-conf.d/munin-node':
#
# [owncloud_*]
# env.dbuser owncloud
# env.dbpassword password
# env.dbname owncloud

envuser=${dbuser:-owncloud}
envpassword=${dbpassword:-password}
envdb=${dbname:-owncloud}

query="SELECT oc_users.uid, IF(oc_preferences.configvalue = 'none', '0', oc_preferences.configvalue) AS configvalue FROM oc_users LEFT JOIN oc_preferences ON oc_preferences.userid = oc_users.uid WHERE oc_preferences.configkey = 'quota' ORDER BY oc_users.uid ASC"

dehumanise() {
  # Owncloud looks to be using powers of 2 in their calculus.
  #     /KB$/{    printpower($1, 10,  3)};
  #     /MB$/{    printpower($1, 10,  6)};
  #     /GB$/{    printpower($1, 10,  9)};
  #     /TB$/{    printpower($1, 10, 12)}'
  for v in "$@"
  do  
    echo $v | tr -d ' ' | awk \
      'BEGIN{IGNORECASE = 1}
       function printpower(n,b,p) {printf "%u\n", n*b^p; next}
       /[0-9]$/{print $1;next};
       /K(iB)?$/{printpower($1,  2, 10)};
       /M(iB)?$/{printpower($1,  2, 20)};
       /G(iB)?$/{printpower($1,  2, 30)};
       /T(iB)?$/{printpower($1,  2, 40)};
       /KB$/{    printpower($1,  2, 10)};
       /MB$/{    printpower($1,  2, 20)};
       /GB$/{    printpower($1,  2, 30)};
       /TB$/{    printpower($1,  2, 40)}'
  done
}

case $1 in
  config)
    echo "graph_title Owncloud users quotas"
    echo "graph_vlabel bytes"
    echo "graph_args --base 1024 -l 0"
    echo "graph_category owncloud"
    echo "graph_info Show the users quotas (none or default are shown as 0)"
    
    mysql --user=$envuser --password=$envpassword --execute="$query" $envdb | while read uid configvalue; do
      if [ "$configvalue" != "configvalue" ]
      then
        echo "$uid.label $uid"
      fi
    done

  exit 0;;
esac

mysql --user=$envuser --password=$envpassword --execute="$query" $envdb | while read uid configvalue; do
  if [ "$configvalue" != "configvalue" ]
  then
    quota=`dehumanise "$configvalue"`
    echo "$uid.value $quota"
  fi
done
