#!/bin/sh

# Sample setup for '/etc/munin/plugin-conf.d/munin-node':
#
# [owncloud_*]
# env.dbuser owncloud
# env.dbpassword password
# env.dbname owncloud

envuser=${dbuser:-owncloud}
envpassword=${dbpassword:-password}
envdb=${dbname:-owncloud}

query="SELECT oc_users.uid, oc_filecache.size FROM oc_users LEFT JOIN oc_mounts ON oc_mounts.user_id = oc_users.uid LEFT JOIN oc_filecache ON oc_filecache.storage = oc_mounts.storage_id WHERE oc_mounts.mount_point = concat(concat('/', oc_users.uid), '/') AND oc_filecache.path = '' ORDER BY oc_users.uid ASC"

case $1 in
  config)
    echo "graph_title Owncloud disk usage"
    echo "graph_vlabel bytes"
    echo "graph_args --base 1024 -l 0"
    echo "graph_category owncloud"
    echo "graph_info The storage disk usage show the disk space usage per user (real size on the disk, including the file, file_trashbin, file_versions and other working folders)."
    
    mysql --user=$envuser --password=$envpassword --execute="$query" $envdb | while read uid size; do
      if [ $size != 'size' ]
      then
        echo "$uid.label $uid"
      fi
    done

  exit 0;;
esac

mysql --user=$envuser --password=$envpassword --execute="$query" $envdb | while read uid size; do
  if [ $size != 'size' ]
  then
    echo "$uid.value $size"
  fi
done
