#!/bin/sh

# Sample setup for '/etc/munin/plugin-conf.d/munin-node':
#
# [cloud_*]
# env.dbuser owncloud
# env.dbpassword password
# env.dbname owncloud
# env.dbtableprefix oc_
# env.quotaratio 0.95

envuser=${dbuser:-owncloud}
envpassword=${dbpassword:-password}
envdb=${dbname:-owncloud}
envtableprefix=${dbtableprefix:-oc_}

envquotaratio=${quotaratio:-0.95}

query="SELECT ${dbtableprefix}users.uid, ${dbtableprefix}filecache.size, IF(${dbtableprefix}preferences.configvalue = 'none', '0', ${dbtableprefix}preferences.configvalue) AS quota FROM ${dbtableprefix}users LEFT JOIN ${dbtableprefix}mounts ON ${dbtableprefix}mounts.user_id = ${dbtableprefix}users.uid LEFT JOIN ${dbtableprefix}filecache ON ${dbtableprefix}filecache.storage = ${dbtableprefix}mounts.storage_id LEFT JOIN ${dbtableprefix}preferences ON ${dbtableprefix}preferences.userid = ${dbtableprefix}users.uid WHERE ${dbtableprefix}mounts.mount_point = concat(concat('/', ${dbtableprefix}users.uid), '/') AND ${dbtableprefix}filecache.path = 'files' AND ${dbtableprefix}preferences.configkey = 'quota' ORDER BY ${dbtableprefix}users.uid ASC"

dehumanise() {
  # Owncloud looks to be using powers of 2 in all their calculus.
  for v in "$@"
  do
    echo $v | tr -d ' ' | awk \
      'BEGIN{IGNORECASE = 1}
       function printpower(n,b,p) {printf "%u\n", n*b^p; next}
       /[0-9]$/{print $1;next};
       /K(iB)?$/{printpower($1,  2, 10)};
       /M(iB)?$/{printpower($1,  2, 20)};
       /G(iB)?$/{printpower($1,  2, 30)};
       /T(iB)?$/{printpower($1,  2, 40)};
       /KB$/{    printpower($1,  2, 10)};
       /MB$/{    printpower($1,  2, 20)};
       /GB$/{    printpower($1,  2, 30)};
       /TB$/{    printpower($1,  2, 40)}'
  done
}
humanise() {
  for v in "$@"
  do
    echo $v | awk \
      'function human(x) {
        if (x<1000) {return x} else {x/=1024}
        s="kMGTEPYZ";
        while (x>=1000 && length(s)>1)
          {x/=1024; s=substr(s,2)}
        return int(x+0.5) substr(s,1,1)
      }
      {sub(/^[0-9]+/, human($1)); print}'
  done
}

case $1 in
  config)
    echo "graph_title Cloud storage usage"
    echo "graph_vlabel bytes"
    echo "graph_args --base 1024 -l 0"
    echo "graph_category cloud"
    echo "graph_info The storage usage show the user storage utilization (size of the file folder, not including the content of file_trashbin or file_versions). For users having a quota set, a critical thresholds is triggered when `echo "scale=0; ($envquotaratio*100)/1" | bc -l`% of the quota usage is reached."
    echo "graph_total Total"

    mysql --user=$envuser --password=$envpassword --execute="$query" $envdb |
    {
      i=0
      while read uid size quota; do
        if [ $size != 'size' ]
        then
          echo "$uid.label $uid"
          quotavalue=`dehumanise "$quota"`
          if [ $quotavalue -gt 0 ]
          then
            echo "$uid.critical `echo "scale=0; ($quotavalue*$envquotaratio)/1" | bc -l`"
            echo "$uid.info Quota is `humanise $quotavalue`"
            if [ $i -eq 0 ]
            then
              echo "$uid.draw AREA"
            else
              echo "$uid.draw STACK"
            fi
            i=$((i+1))
          fi
        fi
      done
    }

  exit 0;;
esac

mysql --user=$envuser --password=$envpassword --execute="$query" $envdb | while read uid size quota; do
  if [ $size != 'size' ]
  then
    echo "$uid.value $size"
  fi
done